modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
    modId = "jmc"
    version = "${version}"
    displayName = "Just More Cakes!"
    #updateJSONURL="http://myurl.me/"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
    issueTrackerURL = "https://github.com/MincraftEinstein/JustMoreCakes/issues"
    logoFile = "pack.png"
    credits = "Me the mod author"
    authors = "MincraftEinstein"
    displayTest = "MATCH_VERSION"
    description = '''
Adds 30 new flavors of cake along with new improvements and mechanics for a better cake experience
'''

[modproperties.jmc]
    catalogueImageIcon = "pack.png"
    configuredBackground = "minecraft:textures/block/bricks.png"

[[dependencies.jmc]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.2.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1, 1.20.2]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "jei"
    mandatory = false
    versionRange = "[15.3.0.4,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.jmc]]
    modId = "cake-chomps"
    mandatory = false
    versionRange = "[0,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.jmc]]
    modId = "roughlyenoughitems"
    mandatory = false
    versionRange = "[12.0.684,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "jade"
    mandatory = false
    versionRange = "[11.8.0,)"
    ordering = "NONE"
    side = "BOTH"

[[depedendies.jmc]]
    modId = "amendments"
    madatory = false
    versionRange = "[1.20-1.1.6)"
    ordering = "NONE"
    side = "BOTH"
