modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://github.com/MincraftEinstein/JustMoreCakes/issues"

[[mods]]
    modId = "jmc"
    version = "${version}"
    displayName = "Just More Cakes!"
    #updateJSONURL="http://myurl.me/"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/just-more-cakes"
    logoFile = "pack.png"
    credits = "Me the mod author"
    authors = "${mod_author}"
    displayTest = "MATCH_VERSION"
    description = "${description}"

[modproperties.jmc]
    catalogueImageIcon = "pack.png"
    configuredBackground = "minecraft:textures/block/bricks.png"

[[dependencies.jmc]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "commonnetworking"
    mandatory = true
    versionRange = "[${networking_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "jei"
    mandatory = false
    versionRange = "[15.3.0.4,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.jmc]]
    modId = "cake-chomps"
    mandatory = false
    versionRange = "[0,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.jmc]]
    modId = "roughlyenoughitems"
    mandatory = false
    versionRange = "[12.0.684,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jmc]]
    modId = "jade"
    mandatory = false
    versionRange = "[11.8.0,)"
    ordering = "NONE"
    side = "BOTH"

[[depedendies.jmc]]
    modId = "amendments"
    madatory = false
    versionRange = "[1.20-1.1.6)"
    ordering = "NONE"
    side = "BOTH"
