@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.effects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;