@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.blocks.candle_cakes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;