@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;