@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.client.renderers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;