@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.client.renderers.blockentities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;