@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.jmc.advancement.criterian;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;